SAMPLE_CASES = [
    {
        'name': 'Vehicle Theft - Major Damage (FRAUD)',
        'data': {
            'months_as_customer': 328,
            'age': 48,
            'policy_number': 521585,
            'policy_bind_date': '2015-03-15',
            'policy_state': 'OH',
            'policy_csl': '250/500',
            'policy_deductable': 1000,
            'policy_annual_premium': 1406.91,
            'umbrella_limit': 0,
            'insured_zip': 466132,
            'insured_sex': 'MALE',
            'insured_education_level': 'MD',
            'insured_occupation': 'craft-repair',
            'insured_hobbies': 'chess',
            'insured_relationship': 'husband',
            'capital-gains': 0,
            'capital-loss': 0,
            'incident_date': '2015-03-01',
            'incident_type': 'Vehicle Theft',
            'collision_type': 'Side Collision',
            'incident_severity': 'Major Damage',
            'authorities_contacted': 'Police',
            'incident_state': 'OH',
            'incident_city': 'Columbus',
            'incident_location': 'Street',
            'incident_hour_of_the_day': 5,
            'number_of_vehicles_involved': 1,
            'property_damage': 'YES',
            'bodily_injuries': 1,
            'witnesses': 2,
            'police_report_available': 'YES',
            'total_claim_amount': 71610,
            'injury_claim': 6510,
            'property_claim': 13020,
            'vehicle_claim': 52080,
            'auto_make': 'Honda',
            'auto_model': 'Civic',
            'auto_year': 2007,
            'claim_ratio': 50.86,
            'claim_per_vehicle': 71610.0,
            'claim_per_injury': 3255.0
        }
    },
    {
        'name': 'Minor Rear Collision (LEGITIMATE)',
        'data': {
            'months_as_customer': 156,
            'age': 35,
            'policy_number': 432187,
            'policy_bind_date': '2018-06-20',
            'policy_state': 'CA',
            'policy_csl': '100/300',
            'policy_deductable': 500,
            'policy_annual_premium': 1120.50,
            'umbrella_limit': 5000000,
            'insured_zip': 90210,
            'insured_sex': 'FEMALE',
            'insured_education_level': 'College',
            'insured_occupation': 'prof-specialty',
            'insured_hobbies': 'reading',
            'insured_relationship': 'own-child',
            'capital-gains': 15000,
            'capital-loss': 0,
            'incident_date': '2024-11-10',
            'incident_type': 'Single Vehicle Collision',
            'collision_type': 'Rear Collision',
            'incident_severity': 'Minor Damage',
            'authorities_contacted': 'Police',
            'incident_state': 'CA',
            'incident_city': 'Los Angeles',
            'incident_location': 'Parking Lot',
            'incident_hour_of_the_day': 14,
            'number_of_vehicles_involved': 2,
            'property_damage': 'NO',
            'bodily_injuries': 0,
            'witnesses': 3,
            'police_report_available': 'YES',
            'total_claim_amount': 2500,
            'injury_claim': 0,
            'property_claim': 500,
            'vehicle_claim': 2000,
            'auto_make': 'Toyota',
            'auto_model': 'Camry',
            'auto_year': 2020,
            'claim_ratio': 2.23,
            'claim_per_vehicle': 1250.0,
            'claim_per_injury': 0.0
        }
    },
    {
        'name': 'Parked Car Hit - Total Loss (FRAUD)',
        'data': {
            'months_as_customer': 89,
            'age': 29,
            'policy_number': 678945,
            'policy_bind_date': '2020-01-05',
            'policy_state': 'FL',
            'policy_csl': '500/1000',
            'policy_deductable': 2000,
            'policy_annual_premium': 2145.75,
            'umbrella_limit': 0,
            'insured_zip': 33101,
            'insured_sex': 'MALE',
            'insured_education_level': 'High School',
            'insured_occupation': 'transport-moving',
            'insured_hobbies': 'exercise',
            'insured_relationship': 'unmarried',
            'capital-gains': 0,
            'capital-loss': 5000,
            'incident_date': '2025-08-22',
            'incident_type': 'Parked Car',
            'collision_type': 'Front Collision',
            'incident_severity': 'Total Loss',
            'authorities_contacted': 'None',
            'incident_state': 'FL',
            'incident_city': 'Miami',
            'incident_location': 'Street',
            'incident_hour_of_the_day': 2,
            'number_of_vehicles_involved': 1,
            'property_damage': 'YES',
            'bodily_injuries': 2,
            'witnesses': 0,
            'police_report_available': 'NO',
            'total_claim_amount': 95000,
            'injury_claim': 25000,
            'property_claim': 20000,
            'vehicle_claim': 50000,
            'auto_make': 'BMW',
            'auto_model': '3 Series',
            'auto_year': 2019,
            'claim_ratio': 44.27,
            'claim_per_vehicle': 95000.0,
            'claim_per_injury': 12500.0
        }
    },
    {
        'name': 'Multi-Vehicle Highway Accident (LEGITIMATE)',
        'data': {
            'months_as_customer': 245,
            'age': 52,
            'policy_number': 889234,
            'policy_bind_date': '2016-09-12',
            'policy_state': 'TX',
            'policy_csl': '250/500',
            'policy_deductable': 1000,
            'policy_annual_premium': 1580.25,
            'umbrella_limit': 10000000,
            'insured_zip': 75001,
            'insured_sex': 'MALE',
            'insured_education_level': 'Masters',
            'insured_occupation': 'exec-managerial',
            'insured_hobbies': 'golf',
            'insured_relationship': 'husband',
            'capital-gains': 45000,
            'capital-loss': 0,
            'incident_date': '2025-03-05',
            'incident_type': 'Multi-vehicle Collision',
            'collision_type': 'Side Collision',
            'incident_severity': 'Major Damage',
            'authorities_contacted': 'Police',
            'incident_state': 'TX',
            'incident_city': 'Dallas',
            'incident_location': 'Highway',
            'incident_hour_of_the_day': 17,
            'number_of_vehicles_involved': 4,
            'property_damage': 'YES',
            'bodily_injuries': 1,
            'witnesses': 5,
            'police_report_available': 'YES',
            'total_claim_amount': 18500,
            'injury_claim': 5000,
            'property_claim': 3500,
            'vehicle_claim': 10000,
            'auto_make': 'Ford',
            'auto_model': 'F-150',
            'auto_year': 2021,
            'claim_ratio': 11.71,
            'claim_per_vehicle': 4625.0,
            'claim_per_injury': 5000.0
        }
    },
    {
        'name': 'Suspicious Fire Damage (FRAUD)',
        'data': {
            'months_as_customer': 42,
            'age': 38,
            'policy_number': 234567,
            'policy_bind_date': '2023-07-15',
            'policy_state': 'NY',
            'policy_csl': '100/300',
            'policy_deductable': 1500,
            'policy_annual_premium': 2890.50,
            'umbrella_limit': 0,
            'insured_zip': 10001,
            'insured_sex': 'FEMALE',
            'insured_education_level': 'Associate',
            'insured_occupation': 'sales',
            'insured_hobbies': 'camping',
            'insured_relationship': 'wife',
            'capital-gains': 0,
            'capital-loss': 12000,
            'incident_date': '2025-12-20',
            'incident_type': 'Vehicle Theft',
            'collision_type': 'Front Collision',
            'incident_severity': 'Total Loss',
            'authorities_contacted': 'Fire',
            'incident_state': 'NY',
            'incident_city': 'New York',
            'incident_location': 'Parking Lot',
            'incident_hour_of_the_day': 3,
            'number_of_vehicles_involved': 1,
            'property_damage': 'YES',
            'bodily_injuries': 0,
            'witnesses': 0,
            'police_report_available': 'NO',
            'total_claim_amount': 85000,
            'injury_claim': 0,
            'property_claim': 15000,
            'vehicle_claim': 70000,
            'auto_make': 'Mercedes',
            'auto_model': 'C-Class',
            'auto_year': 2018,
            'claim_ratio': 29.41,
            'claim_per_vehicle': 85000.0,
            'claim_per_injury': 0.0
        }
    },
    {
        'name': 'Simple Fender Bender (LEGITIMATE)',
        'data': {
            'months_as_customer': 412,
            'age': 44,
            'policy_number': 998877,
            'policy_bind_date': '2012-03-28',
            'policy_state': 'WA',
            'policy_csl': '100/300',
            'policy_deductable': 500,
            'policy_annual_premium': 985.00,
            'umbrella_limit': 2000000,
            'insured_zip': 98101,
            'insured_sex': 'MALE',
            'insured_education_level': 'College',
            'insured_occupation': 'tech-support',
            'insured_hobbies': 'movies',
            'insured_relationship': 'husband',
            'capital-gains': 8000,
            'capital-loss': 0,
            'incident_date': '2025-10-15',
            'incident_type': 'Single Vehicle Collision',
            'collision_type': 'Rear Collision',
            'incident_severity': 'Trivial Damage',
            'authorities_contacted': 'None',
            'incident_state': 'WA',
            'incident_city': 'Seattle',
            'incident_location': 'Parking Lot',
            'incident_hour_of_the_day': 10,
            'number_of_vehicles_involved': 2,
            'property_damage': 'NO',
            'bodily_injuries': 0,
            'witnesses': 2,
            'police_report_available': 'NO',
            'total_claim_amount': 800,
            'injury_claim': 0,
            'property_claim': 0,
            'vehicle_claim': 800,
            'auto_make': 'Honda',
            'auto_model': 'Accord',
            'auto_year': 2022,
            'claim_ratio': 0.81,
            'claim_per_vehicle': 400.0,
            'claim_per_injury': 0.0
        }
    }
]
